name: Build Repo on Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Ensure this version is correctly specified

    - name: Build project
      run: dotnet build ztrm.sln --configuration Release --output ./build_output

    - name: Zip the build output
      run: Compress-Archive -Path ./build_output/* -DestinationPath ./build_output/ztrm.zip

    - name: Upload Artifacts to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./build_ouput/ztrm.zip
        asset_name: ztrm.zip
        asset_content_type: application/zip
